### ISSUE TITLE
Using the original texture sources.

### ISSUE THREAD

**Issue by snigelpasta** [TechieAndroid/sm64redrawn#4]
Since some of the original assets Nintendo used for the textures have been discovered, does this project plan on using these as sources?

https://knowyourmeme.com/photos/1872683-2020-nintendo-source-code-gigaleak

**Comment by TechieAndroid** [comment]
I remember back when we were discussing it in the discord server and those textures, if I'm remembering correctly, came from SGI's proprietary system at the time, that Nintendo was making the game on.

The images are real life objects like gravel and the saw dust/wood chippings, if you put those hi res images into the game it doesn't look very good. Considering how the N64 had a limited amount of video memory it made sense to scale them down at the time and that worked out fine since you couldn't really make out what those textures were and nobody really knew that they were actually photos, so it worked well to use low quality images for walls and floors.

So to answer your question, no we won't be using those images directly, but maybe more like as a reference to go off of for making some textures that feels more natural to the game while still keeping the iconic look and feel the game has.

If you have any other questions feel free to hit me up here or on the discord channel. I may not be that active on the project right now but I'm still here and when I have some free time (and working hardware to make more textures) I plan to continue to improve the project as much as possible.
