### ISSUE TITLE
How to add mods to Super Mario 64 NX?

### ISSUE THREAD

**Issue by CristinaTheGamer** [TechieAndroid/sm64redrawn#6]
I was trying to download a local texutre mod pak, but realized later on that the Super Mario 64 NX app requires a .pak file to add more mods. However upon looking at the texture pack folder that I downloaded, I cannot find a pak file anywhere, and cannot install the new texture mod. Can you please help me?:(

**Comment by TechieAndroid** [comment]
Hm, I never used the NX version but I did make a pak with textures, and that can be found in the readme if you scroll down a bit there is a Google drive link to it. I just checked and it's still a good link.

I had to do it like that because of the size limit on GitHub uploads if I remember correctly.

**Comment by AexHar** [comment]
Hi I just wanted to know how can I make a pak file ?

**Comment by TechieAndroid** [comment]
> Hi I just wanted to know how can I make a pak file ?

Here's how I did it:
cd into the gfx folder, then run
pak.py --source . --output redrawn.pak

And for more control of texture size:
pak.py --source . --output redrawn.pak --max-size 256
